// Recipe data with tags for search and filtering
const recipesData = [
  {"slug": "15-minute-egg-fried-rice-with-frozen-veg", "name": "15-Minute Egg Fried Rice with Frozen Veg", "time": 15, "cal": 410, "tags": ["dinner", "lunch", "vegetarian", "quick"]},
  {"slug": "baked-bbq-chicken-thighs-with-roasted-potatoes", "name": "Baked BBQ Chicken Thighs with Roasted Potatoes", "time": 45, "cal": 610, "tags": ["dinner", "chicken"]},
  {"slug": "bbq-chicken-sweet-potato-skillet", "name": "BBQ Chicken Sweet Potato Skillet", "time": 37, "cal": 540, "tags": ["dinner", "chicken"]},
  {"slug": "beef-taco-rice-skillet", "name": "Beef Taco Rice Skillet", "time": 35, "cal": 640, "tags": ["dinner", "beef"]},
  {"slug": "black-bean-sweet-potato-skillet", "name": "Black Bean Sweet Potato Skillet", "time": 35, "cal": 440, "tags": ["dinner", "lunch", "vegetarian"]},
  {"slug": "chicken-fajita-sheet-pan-bowls", "name": "Chicken Fajita Sheet-Pan Bowls", "time": 30, "cal": 480, "tags": ["dinner", "lunch", "chicken", "quick"]},
  {"slug": "chickpea-tomato-stew-with-rice", "name": "Chickpea & Tomato Stew with Rice", "time": 35, "cal": 460, "tags": ["dinner", "lunch", "vegetarian"]},
  {"slug": "classic-turkey-smash-burgers-with-secret-sauce", "name": "Classic Turkey Smash Burgers with Secret Sauce", "time": 20, "cal": 560, "tags": ["dinner", "lunch", "turkey", "quick"]},
  {"slug": "cottage-cheese-veggie-egg-bake", "name": "Cottage Cheese Veggie Egg Bake", "time": 50, "cal": 260, "tags": ["breakfast", "vegetarian"]},
  {"slug": "creamy-garlic-bliss", "name": "Creamy Garlic Bliss", "time": 25, "cal": 699, "tags": ["dinner", "vegetarian", "quick"]},
  {"slug": "creamy-lemon-chicken-orzo-one-pot", "name": "Creamy Lemon Chicken Orzo (One Pot)", "time": 35, "cal": 520, "tags": ["dinner", "chicken"]},
  {"slug": "creamy-tomato-tortellini-with-spinach", "name": "Creamy Tomato Tortellini with Spinach", "time": 20, "cal": 560, "tags": ["dinner", "vegetarian", "quick"]},
  {"slug": "crispy-fish-tacos-with-lime-slaw", "name": "Crispy Fish Tacos with Lime Slaw", "time": 25, "cal": 510, "tags": ["dinner", "lunch", "seafood", "quick"]},
  {"slug": "egg-fried-rice-with-frozen-veggies", "name": "Egg Fried Rice with Frozen Veggies", "time": 20, "cal": 420, "tags": ["dinner", "lunch", "vegetarian", "quick"]},
  {"slug": "garlic-ginger-beef-broccoli-stir-fry", "name": "Garlic-Ginger Beef & Broccoli Stir-Fry", "time": 27, "cal": 520, "tags": ["dinner", "beef", "quick"]},
  {"slug": "garlic-parmesan-chickpea-pasta", "name": "Garlic Parmesan Chickpea Pasta", "time": 25, "cal": 520, "tags": ["dinner", "lunch", "vegetarian", "quick"]},
  {"slug": "ginger-soy-salmon-with-sesame-broccoli", "name": "Ginger-Soy Salmon with Sesame Broccoli", "time": 25, "cal": 470, "tags": ["dinner", "seafood", "quick"]},
  {"slug": "gochujang-sweet-potato-breakfast-hash-kimchi-yogurt", "name": "Gochujang Sweet Potato Breakfast Hash with Kimchi Yogurt", "time": 40, "cal": 520, "tags": ["breakfast", "vegetarian"]},
  {"slug": "greek-avgolemono-white-bean-stew-charred-lemon", "name": "Greek Avgolemono White Bean Stew with Charred Lemon", "time": 50, "cal": 490, "tags": ["dinner", "vegetarian"]},
  {"slug": "greek-chicken-souvlaki-bowls-quick-marinade", "name": "Greek Chicken Souvlaki Bowls (Quick Marinade)", "time": 27, "cal": 560, "tags": ["dinner", "lunch", "chicken", "quick"]},
  {"slug": "greek-miso-style-grilled-eggplant-walnut-skordalia-cherry-tomato-relish", "name": "Greek Miso-Style Grilled Eggplant with Walnut Skordalia", "time": 45, "cal": 530, "tags": ["dinner", "vegetarian"]},
  {"slug": "greek-spanakopita-waffles-with-lemon-dill-yogurt", "name": "Greek Spanakopita Waffles with Lemon-Dill Yogurt", "time": 35, "cal": 510, "tags": ["breakfast", "lunch", "vegetarian"]},
  {"slug": "honey-soy-ground-pork-lettuce-bowls", "name": "Honey Soy Ground Pork Lettuce Bowls", "time": 22, "cal": 460, "tags": ["dinner", "lunch", "pork", "quick"]},
  {"slug": "honey-sriracha-salmon-with-edamame-rice", "name": "Honey-Sriracha Salmon with Edamame Rice", "time": 25, "cal": 560, "tags": ["dinner", "seafood", "quick"]},
  {"slug": "indian-coconut-peanut-saag-charred-broccoli-paneer-croutons", "name": "Indian Coconut-Peanut Saag with Paneer", "time": 45, "cal": 560, "tags": ["dinner", "vegetarian"]},
  {"slug": "indian-spiced-chickpea-chaat-jar-salad-tamarind-date-dressing", "name": "Indian Spiced Chickpea Chaat Jar Salad", "time": 20, "cal": 420, "tags": ["lunch", "snack", "vegetarian", "quick"]},
  {"slug": "indian-tandoori-style-salmon-curry-leaf-brown-butter-cabbage-thoran", "name": "Indian Tandoori-Style Salmon", "time": 35, "cal": 590, "tags": ["dinner", "seafood"]},
  {"slug": "korean-barley-bibim-salad-perilla-pesto-roasted-carrots", "name": "Korean Barley Bibim Salad", "time": 50, "cal": 460, "tags": ["lunch", "vegetarian"]},
  {"slug": "korean-doenjang-butter-clams-scallion-gremolata", "name": "Korean Doenjang Butter Clams", "time": 27, "cal": 410, "tags": ["dinner", "seafood", "quick"]},
  {"slug": "korean-inspired-beef-bulgogi-lettuce-wraps", "name": "Korean-Inspired Beef Bulgogi Lettuce Wraps", "time": 25, "cal": 430, "tags": ["dinner", "lunch", "beef", "quick"]},
  {"slug": "lemon-garlic-chicken-quinoa-bowls", "name": "Lemon-Garlic Chicken Quinoa Bowls", "time": 35, "cal": 510, "tags": ["dinner", "lunch", "chicken"]},
  {"slug": "lemon-herb-tuna-pasta-salad", "name": "Lemon Herb Tuna Pasta Salad", "time": 25, "cal": 480, "tags": ["lunch", "seafood", "quick"]},
  {"slug": "lemony-lentil-soup-with-spinach", "name": "Lemony Lentil Soup with Spinach", "time": 45, "cal": 320, "tags": ["dinner", "lunch", "vegetarian"]},
  {"slug": "lentil-sloppy-joes", "name": "Lentil Sloppy Joes", "time": 35, "cal": 390, "tags": ["dinner", "lunch", "vegetarian"]},
  {"slug": "mediterranean-chickpea-tuna-salad-pitas", "name": "Mediterranean Chickpea & Tuna Salad Pitas", "time": 15, "cal": 430, "tags": ["lunch", "seafood", "quick"]},
  {"slug": "one-pot-turkey-taco-rice", "name": "One-Pot Turkey Taco Rice", "time": 35, "cal": 470, "tags": ["dinner", "turkey"]},
  {"slug": "peanut-chicken-noodle-party", "name": "Peanut Chicken Noodle Party", "time": 15, "cal": 407, "tags": ["dinner", "lunch", "chicken", "quick"]},
  {"slug": "pesto-veggie-pasta-with-white-beans", "name": "Pesto Veggie Pasta with White Beans", "time": 25, "cal": 590, "tags": ["dinner", "vegetarian", "quick"]},
  {"slug": "pork-cabbage-stir-fry-with-garlic-noodles", "name": "Pork & Cabbage Stir-Fry with Garlic Noodles", "time": 27, "cal": 660, "tags": ["dinner", "pork", "quick"]},
  {"slug": "quick-beef-and-cabbage-stir-fry", "name": "Quick Beef and Cabbage Stir-Fry", "time": 25, "cal": 490, "tags": ["dinner", "beef", "quick"]},
  {"slug": "sheet-pan-chicken-fajitas", "name": "Sheet Pan Chicken Fajitas", "time": 30, "cal": 430, "tags": ["dinner", "chicken", "quick"]},
  {"slug": "sheet-pan-sausage-peppers-potatoes", "name": "Sheet-Pan Sausage, Peppers & Potatoes", "time": 42, "cal": 610, "tags": ["dinner", "pork"]},
  {"slug": "sheet-pan-sausage-potatoes-cabbage", "name": "Sheet Pan Sausage, Potatoes & Cabbage", "time": 40, "cal": 540, "tags": ["dinner", "pork"]},
  {"slug": "southern-buttermilk-cornbread-panzanella-pickled-okra-vinaigrette", "name": "Southern Buttermilk Cornbread Panzanella", "time": 30, "cal": 480, "tags": ["lunch", "vegetarian", "quick"]},
  {"slug": "southern-shrimp-and-grits-stuffed-peppers-creole-tomato-jam", "name": "Southern Shrimp and Grits Stuffed Peppers", "time": 60, "cal": 640, "tags": ["dinner", "seafood"]},
  {"slug": "southern-sorghum-glazed-pork-chops-mustard-greens-pickled-peach", "name": "Southern Sorghum-Glazed Pork Chops", "time": 40, "cal": 610, "tags": ["dinner", "pork"]},
  {"slug": "teriyaki-tofu-vegetable-rice-bowls", "name": "Teriyaki Tofu & Vegetable Rice Bowls", "time": 35, "cal": 520, "tags": ["dinner", "lunch", "vegetarian"]},
  {"slug": "thai-lemongrass-coconut-rice-congee-soft-egg-chili-crisp", "name": "Thai Lemongrass Coconut Rice Congee", "time": 45, "cal": 430, "tags": ["breakfast", "vegetarian"]},
  {"slug": "thai-red-curry-mussels-basil-corn-broth", "name": "Thai Red Curry Mussels", "time": 30, "cal": 520, "tags": ["dinner", "seafood", "quick"]},
  {"slug": "thai-tamarind-black-pepper-turkey-larb-crispy-rice-herbs", "name": "Thai Tamarind-Black Pepper Turkey Larb", "time": 35, "cal": 540, "tags": ["dinner", "lunch", "turkey"]},
  {"slug": "tuna-white-bean-lemon-pasta", "name": "Tuna White Bean Lemon Pasta", "time": 25, "cal": 520, "tags": ["dinner", "lunch", "seafood", "quick"]},
  {"slug": "turkey-black-bean-chili-30-minute", "name": "Turkey & Black Bean Chili (30-Minute)", "time": 30, "cal": 480, "tags": ["dinner", "turkey", "quick"]}
];

// Export for Node.js or use directly in browser
if (typeof module !== 'undefined') module.exports = recipesData;
